export {userReducer, setUser, initUser, logout} from './model/slices/userSlice'
export {getIsAuth} from './model/selectors/getIsAuth'
export {getIsInitUser} from './model/selectors/getIsInitUser'
export {getUserData} from './model/selectors/getUserData'
export { UserSchema } from './model/types/types'
